services:
  webserver:
    #image: "moodlehq/moodle-php-apache:${MOODLE_DOCKER_PHP_VERSION}"
    image: "tugboatqa/php:8-apache"
    default: true
    depends_on:
      - db
    commands:
      init:
        - echo "****** initializing webserver *****"
        
        - sudo apt-get update
        #- sudo apt-get install php-mysql
        #- sudo apt-get install default-mysql-client
        #- sudo apt-get --with-mysqli install mariadb-client
        - docker-php-ext-install mysqli
        
        - echo "SetEnv MOODLE_DOCKER_DB mariadb" >> /etc/apache2/conf-available/env.conf
        - echo "SetEnv MOODLE_DOCKER_DBTYPE mariadb" >> /etc/apache2/conf-available/env.conf
        - echo "SetEnv MOODLE_DOCKER_DBCOLLATION utf8mb4_bin" >> /etc/apache2/conf-available/env.conf
        - echo "SetEnv MOODLE_DOCKER_DBNAME moodle" >> /etc/apache2/conf-available/env.conf
        - echo "SetEnv MOODLE_DOCKER_DBUSER moodle" >> /etc/apache2/conf-available/env.conf
        - echo "SetEnv MOODLE_DOCKER_DBPASS m00dl3ing" >> /etc/apache2/conf-available/env.conf
        #- service apache2 reload
        
        # Link the document root to the expected path. This example links /moodle
        # to the docroot.
        #Note: the TUGBOAT_ROOT environment variable is equivalent to the git repo root.
        - ln -snf "$TUGBOAT_ROOT" "${DOCROOT}"

        #- echo "php extensions"
        #- php -m
        
        #- cp "${TUGBOAT_ROOT}/.tugboat/config.php" "${DOCROOT}/config.php"
        
        #make required dirs and set permissions.
        - mkdir /var/www/moodledata
        - mkdir /var/www/phpunitdata
        - mkdir /var/www/behatdata
        - mkdir /var/www/behatfaildumps
        - chmod 0777 /var/www/moodledata
        
      build:
      #  - npm install
      #  - npx grunt
      # Install/update packages managed by composer, including drush.
        - composer install --optimize-autoloader --ignore-platform-req=ext-zip --ignore-platform-req=ext-intl
        
      update:
        - service apache2 start
      #  - cp "${TUGBOAT_ROOT}/.tugboat/config.php" "${DOCROOT}/config.php"
    
  db:
    image: "tugboatqa/mariadb:10.7"
    commands:
      init:
        - mysql -e "SET GLOBAL character_set_server=utf8mb4;"
        - mysql -e "SET GLOBAL collation_server=utf8mb4_bin;"
        - mysql -e "SET GLOBAL innodb_file_per_table=ON;"
        - mysql -e "SET GLOBAL wait_timeout=28800;"
        # - mysql -e "SET GLOBAL disable_log_bin=ON;"
        - export MYSQL_ROOT_PASSWORD=m00dl3ing
        - export MYSQL_DATABASE=moodle
        - export MYSQL_USER=moodle
        - export MYSQL_PASSWORD=m00dl3ing
        #- mysql -e "CREATE DATABASE IF NOT EXISTS moodle; GRANT ALL PRIVILEGES ON moodle.* TO 'moodle'@'%' IDENTIFIED BY 'moodl3ing'; FLUSH PRIVILEGES;"
        - mysql -e "CREATE DATABASE IF NOT EXISTS moodle; GRANT ALL PRIVILEGES ON moodle.* TO 'moodle'@'%' IDENTIFIED BY 'moodl3ing';"
        - mysql -e "ALTER USER 'tugboat'@'%' IDENTIFIED WITH mysql_native_password BY 'tugboat';"
    #ports:
    #  - "${MOODLE_DOCKER_DB_PORT}:3306/tcp"

  phpmyadmin:
    expose: 80
    image: phpmyadmin/phpmyadmin
