services:
  webserver:
    #image: "moodlehq/moodle-php-apache:${MOODLE_DOCKER_PHP_VERSION}"
    image: "tugboatqa/php:8-apache"
    default: true
    depends_on:
      - db
    environment:
      MOODLE_DOCKER_RUNNING: 1
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: "m@0dl3ing"
      MOODLE_DOCKER_BROWSER: firefox
    commands:
      init:
        - ln -snf "$TUGBOAT_ROOT/moodle" "/var/www/html"
      update:
    
  db:
    image: "tugboatqa/mariadb:10.7"
    #image: "mariadb:${MOODLE_DOCKER_DB_VERSION:-10.7}"
    command: >
              --character-set-server=utf8mb4
              --collation-server=utf8mb4_bin
              --innodb_file_per_table=On
              --wait-timeout=28800
              --skip-log-bin
    environment:
      MYSQL_ROOT_PASSWORD: "m@0dl3ing"
      MYSQL_DATABASE: "moodle"
      MYSQL_USER: "moodle"
      MYSQL_PASSWORD: "m@0dl3ing"
    ports:
      - "${MOODLE_DOCKER_DB_PORT}:3306/tcp"
