services:
  webserver:
    image: "tugboatqa/php:8.3-apache"
    default: true
    checkout_path: "/var/www/moodle"
    depends_on:
      - db
    commands:
      init:
        - echo "****** initializing webserver *****"
        - echo "****** installing required php extensions *****"
        - apt-get update && apt-get install -y libzip-dev libldap2-dev libmemcached-dev libmsgpack-dev libpspell-dev unzip git libxml2-dev libcurl4-openssl-dev libxslt-dev
        - pecl install redis solr
        - docker-php-ext-install mysqli zip soap intl exif ldap ffi ftp gettext pspell shmop sockets sysvmsg sysvsem sysvshm xsl
        - docker-php-ext-enable redis solr

        - echo "****** initializing the submodules *****"
        #- git config submodule.admin/tool/ucsfsomapi.url https://${GITHUB_TOKEN_USER}:${GITHUB_TOKEN}@github.com/ucsf-education/tool_ucsfsomapi.git
        - git submodule update --init

        - echo "****** Setting php config variables ******"
        - echo "max_input_vars = 5000" >> /usr/local/etc/php/conf.d/max_input_vars.ini
               
        # Link the document root to the expected path.
        - ln -snf "$TUGBOAT_ROOT" "${DOCROOT}"
        
        #make required dirs and set permissions.
        - mkdir /var/www/moodledata
        - mkdir /var/www/phpunitdata
        - mkdir /var/www/behatdata
        - mkdir /var/www/behatfaildumps
        - chmod 0777 /var/www/moodledata

      update:
        - echo "****** updating webserver *****"
        - composer install --optimize-autoloader --ignore-platform-req=ext-zip --ignore-platform-req=ext-intl
        - service apache2 start
      
      build:      
      #  - npm install
      #  - npx grunt
        - echo "****** building webserver *****"
        - chown www-data $DOCROOT
        - |
          sudo -u www-data php admin/cli/install.php \
          --non-interactive --agree-license --lang=en \
          --wwwroot=https://${TUGBOAT_DEFAULT_SERVICE_URL_HOST} \
          --dataroot=/var/www/moodledata \
          --dbtype=${MOODLE_DBTYPE} --dbhost=db --dbname=${MOODLE_DBNAME} --dbuser=${MOODLE_DBUSER} --dbpass=${MOODLE_DBPASS} --prefix=m_ \
          --adminuser=${MOODLE_DBADMIN_NAME} --adminpass=${MOODLE_DBADMIN_PASS} \
          --fullname=PREVIEW --shortname=PREVIEW --adminemail=${MOODLE_ADMIN_EMAIL}
        - chown -R root $DOCROOT
      
      online:
      #  - php admin/tool/generator/cli/maketestsite.php --size=S --bypasscheck
        - |
          if [ "${GENERATE_TEST_DATA:-true}" = "true" ]; then
            php admin/tool/generator/cli/maketestsite.php --size=S --bypasscheck
          fi
        
  db:
    image: "tugboatqa/mariadb:10.11.8"
    depends_on:
      - db-import
    commands:
      init:
        - echo "*** intializing database ***"

        - mysql --max_allowed_packet=1073741824
        #- mysql -e "SET GLOBAL max_allowed_packet=1073741824;"
        - mysql -e "SET GLOBAL character_set_server=utf8mb4;"
        - mysql -e "SET GLOBAL collation_server=utf8mb4_bin;"
        - mysql -e "SET GLOBAL innodb_file_per_table=ON;"
        - mysql -e "SET GLOBAL wait_timeout=28800;"
        - export MYSQL_ROOT_PASSWORD=${MOODLE_DBPASS}
        - export MYSQL_DATABASE=${MOODLE_DBNAME}
        - export MYSQL_USER=${MOODLE_DBUSER}
        - export MYSQL_PASSWORD=${MOODLE_DBPASS}
        - mysql -e "CREATE DATABASE IF NOT EXISTS ${MOODLE_DBNAME}; GRANT ALL PRIVILEGES ON moodle.* TO '${MOODLE_DBNAME}'@'%' IDENTIFIED BY '${MOODLE_DBPASS}'; FLUSH PRIVILEGES;"

  db-import:
    image: "tugboatqa/ubuntu:latest"
    commands:
      init:
        - |
          if [ "${GENERATE_TEST_DATA:-true}" = "false" ]; then
            # Install required tools
            echo "Installing required tools for S3 download..."
            apt-get update
            apt-get install -y python3-full python3-venv mysql-client

            # Creaet and activate a virtual environment
            python3 -m venv /tmp/venv
            . /tmp/venv/bin/activate

            # Install AWS CLI
            echo "Installing AWS CLI..."
            pip install awscli
            #pip3 install awscli
            
            # Configure AWS credentials
            echo "Configuring AWS credentials..."
            export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
            export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY}
                        
            # Download database from S3
            echo "Downloading database from S3..."
            aws s3 cp ${MOODLE_PREVIEW_DB_DOWNLOAD_URL} /tmp/database.sql.gz
                                    
            # Import the database
            echo "Importing database..."
            gunzip -c /tmp/database.sql.gz | mysql -h db -u ${MOODLE_DBUSER} -p${MOODLE_DBPASS} ${MOODLE_DBNAME}
            #gunzip -l /tmp/database.sql.gz
            #mysql -h db -u ${MOODLE_DBUSER} -p${MOODLE_DBPASS} ${MOODLE_DBNAME}            
            
            # Clean up
            rm /tmp/database.sql.gz
            #rm -f /tmp/database.sql.gz /tmp/import.log
            deactivate
            rm -rf /tmp/venv

          else
            echo "Skipping db import. Genertaing testing data..."
            exit 0
          fi
