services:
  webserver:
    #image: "moodlehq/moodle-php-apache:${MOODLE_DOCKER_PHP_VERSION}"
    image: "tugboatqa/php:8-apache"
    default: true
    depends_on:
      - db
    environment:
      MOODLE_DOCKER_RUNNING: 1
      MOODLE_DOCKER_DB: mariadb
      MOODLE_DOCKER_DBTYBE: mariadb     
      MOODLE_DOCKER_DBCOLLATION: utf8mb4_bin
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: "m@0dl3ing"
      MOODLE_DOCKER_BROWSER: firefox
    commands:
      init:
        - echo "initializing webserver"
        - env
        - export MOODLE_DOCKER_DBTYBE=mariadb
        - env
        
        # Link the document root to the expected path. This example links /moodle
        # to the docroot.
        #Note: the TUGBOAT_ROOT environment variable is equivalent to the git repo root.
        - ln -snf "$TUGBOAT_ROOT" "${DOCROOT}"

        - echo "php extensions"
        - php -m
        
        - cp "${TUGBOAT_ROOT}/.tugboat/config.php" "${DOCROOT}/config.php"
        
        #make required dirs and set permissions.
        - mkdir /var/www/moodledata
        - mkdir /var/www/phpunitdata
        - mkdir /var/www/behatdata
        - mkdir /var/www/behatfaildumps
        - chmod 0777 /var/www/moodledata

        - pwd
        - cd ${DOCROOT}
        - pwd

        # Install/update packages managed by composer, including drush.
        - composer install --optimize-autoloader --ignore-platform-req=ext-zip --ignore-platform-req=ext-intl  
        
      build:
        - echo "building..."
        - env
        - export MOODLE_DOCKER_DBTYBE=mariadb
        - echo "env again in build"
        - end
      #update:
      #  - cp "${TUGBOAT_ROOT}/.tugboat/config.php" "${DOCROOT}/config.php"
    
  db:
    image: "tugboatqa/mariadb:10.7"
    #image: "mariadb:${MOODLE_DOCKER_DB_VERSION:-10.7}"
    command: >
              --character-set-server=utf8mb4
              --collation-server=utf8mb4_bin
              --innodb_file_per_table=On
              --wait-timeout=28800
              --skip-log-bin
    environment:
      MYSQL_ROOT_PASSWORD: "m@0dl3ing"
      MYSQL_DATABASE: "moodle"
      MYSQL_USER: "moodle"
      MYSQL_PASSWORD: "m@0dl3ing"
    #ports:
    #  - "${MOODLE_DOCKER_DB_PORT}:3306/tcp"
