name: Deploy branch to sandbox

on:
  workflow_dispatch:

jobs:
  moodle-sandbox-deploy:
    
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: ucsf-education/moodle4ucsf
          event-type: moodle-sandbox-deploy
          # the referring repo, the commit sha, and the branch name
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repository": "${{ github.repository }}"}'