name: UCSFCLE Merge Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - UCSFCLE_[0-9]+_STABLE
  
  
  push:
    branches:
      - "*"

  workflow_dispatch:
  
env:
  sandbox: moodle-sandbox  
  stage: moodle-stage
  ng-stage: moodle-ng-stage
  
jobs:
  trigger-staging-deployment:
    if: >
      github.repository == 'ucsf-education/moodle' && 
      github.event.pull_request.merged == true && 
      github.ref_name == github.event.repository.default_branch
    name: Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Set Event Type
        id: set_event_type
        run: |
          if [[ "${{ github.ref_name }}" == "${{ github.event.repository.default_branch }}" ]]; then
            echo "event_type=${{ env.stage}}" >> $GITHUB_ENV
          else
            echo "event_type=${{ env.ng-stage}}" >> $GITHUB_ENV
          fi     
      - name: Trigger Branch Deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DEPLOYMENT_AUTOMATION_PAT }}
          repository: ucsf-education/cle-devops
          event-type: ${{ env.event_type }}
          client-payload: >            
            {
                "deploy_type": "branch",
                "deploy_branch": "${{ github.ref_name }}",
                "deploy_ref": "${{ github.ref }}",
                "destination":"${{ env.stage }}", 
                "pr_number": "${{ github.event.pull_request.number }}", 
                "merged_by": "${{ github.event.pull_request.merged_by.login }}",
                "title": "${{ github.event.pull_request.title }}",
                "repository": "${{ github.repository }}"
            }

  trigger-sandbox-deployment:
    if: >
      github.repository == 'ucsf-education/moodle' && 
      ( contains(github.event.pull_request.labels.*.name, 'deploy-to-sandbox') || contains(github.event.pull_request.labels.*.name, 'deploy-to-ngsandbox') )
    name: Deploy to Sandbox
    runs-on: ubuntu-latest
    steps: 
      - name: Set Event Type
        id: set_event_type
        run: |
          if [[ "${{ contains(github.event.pull_request.labels.*.name, 'deploy-to-sandbox') }}" ]]; then
            echo "event_type=${{ env.sandbox}}" >> $GITHUB_ENV
          elif [[ "${{ contains(github.event.pull_request.labels.*.name, 'deploy-to-ngsandbox') }}" ]]; then
            echo "event_type=${{ env.ng-stage}}" >> $GITHUB_ENV
          fi     
      - name: Trigger PR Deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DEPLOYMENT_AUTOMATION_PAT }}
          repository: ucsf-education/cle-devops
          event-type: ${{ github.event.pull_request.labels.*.name }}
          client-payload: >            
            {
                "deploy_type": "pull_request",
                "deploy_branch": "${{ github.event.pull_request.head }}",
                "deploy_ref": "${{ github.event.pull_request.head.sha }}",
                "deploy_repo": "${{ github.event.pull_request.head.repo.clone_url}}"
                "is_fork": "${{ github.event.pull_request.head.repo.fork }}",
                "destination":"${{ env.sandbox }}",                 
                "pr_number": "${{ github.event.pull_request.number }}",
                "labeled_by": "${{ github.actor}}"                                 
                "title": "${{ github.event.pull_request.title }}",
                "repository": "${{ github.repository }}"
            } 