name: UCSFCLE Moodle Staging Deployment

on:
  pull_request:
    types: [closed]
    branches:
      - UCSFCLE_[0-9]+_STABLE
  workflow_dispatch:
    inputs:
      destination:
        description: 'Destination environment'
        required: true
        default: 'moodle-stage'
        type: choice
        options:
          - 'moodle-stage'
          - 'moodle-ng-stage'

jobs:
  trigger-staging-deployment:
    if: >
      github.repository == 'ucsf-education/moodle' && 
      (github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch')    
    name: Trigger Moodle Deploy to Staging Environment
    runs-on: ubuntu-latest
    
    steps:   
      - name: CLE DevOps Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DEPLOYMENT_AUTOMATION_PAT }}
          repository: "ucsf-education/cle-devops"
          event-type: "moodle-stage-deploy"
          client-payload: >            
            {
                "deploy_type": "branch",        
                "deploy_ref": "${{ github.ref_name }}",
                "destination": "${{ github.event_name == 'workflow_dispatch' && inputs.destination || (github.ref_name == github.event.repository.default_branch && 'moodle-stage' || 'moodle-ng-stage') }}", 
                "pr_number": "${{ github.event.pull_request.number }}", 
                "merged_by": "${{ github.event.pull_request.merged_by.login }}",
                "title": "${{ github.event.pull_request.title }}"
            }